name: Run demo with kai client and evaluate results

on: push

jobs:
  test-and-evaluate:
    name: Run e2e test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Visual Studio Build Tools
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install visualstudio2022buildtools --params "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --includeRecommended --quiet --wait"

      - name: Install Windows SDK
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install windows-sdk-10.0 -y

      - name: Install Windows Build Tools
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install windows-build-tools -y

      - uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up venv
        run: |
          python -m venv venv
          . venv\Scripts\activate
          echo PATH=C:\\Program Files\\Git\\bin;$PATH >> $GITHUB_ENV

      - name: Set up dependencies
        run: |
          cd kai-client-ci
          pip install -r requirements.txt
        env:
          PATH: ${{ env.PATH }}

      - name: Run execution & evaluation test
        run: |
          echo ${{ env.PATH }}
          python --version
          cd kai-client-ci
          python ./main.py
        env:
          PATH: "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.19041.0\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64;C:\\Program Files\\Git\\bin;$PATH"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          GIT_PYTHON_GIT_EXECUTABLE: "C:\\Program Files\\Git\\bin\\git.exe"