name: Windows Nightly Run

on: [push]

jobs:
  clone_repo:
    runs-on: ubuntu-latest # The action will run on a Linux runner first
    
    steps:
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Install Node.js using Chocolatey on EC2 Windows instance
      run: |
        sshpass -p "pass123!" ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} 'powershell -Command "choco install nodejs -y"
    
    - name: Clone repository on EC2 Windows instance using SSH password
      run: |
        sshpass -p "pass123!" ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} 'powershell -Command "Start-Process -FilePath C:\\Users\\nonadmin\\clone-repo.bat -NoNewWindow -Wait"'
      env:
        EC2_USER: nonadmin
        EC2_HOST: ec2-52-90-29-139.compute-1.amazonaws.com
        EC2_PASSWORD: pass123!
